[package]
name = "bevy-tanks-app"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bevy-tanks-systems.path = "../bevy-tanks-systems"

bevy.workspace = true
bevy-inspector-egui.workspace = true
bevy_rand.workspace = true
bevy_rapier3d.workspace = true
bevy-tnua.workspace = true
bevy-tnua-rapier3d.workspace = true
log.workspace = true
